export const USERS_ROUTE = '/users'
export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '/'
export const USER_PROFILE_ROUTE = '/profile/:userId'
export const FRIENDS_ROUTE = '/friends'
export const MUSIC_ROUTE = '/music'
export const NEW_RELEASES_ROUTE = '/new_releases'